Default: &defaults
  database: BelSES.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: BelSES_test.sqlite3
  <<: *defaults

Staging:
  database: BelSES_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: BelSES_production.sqlite3
  poolsize: 100
  <<: *defaults
